### ISSUE TITLE
Camera 'Allow' button gets disabled

### ISSUE THREAD

**Issue by satnam-malhotra** [google/google-authenticator-android#104]
Steps to reproduce on an android device:
1. Allow camera access during first time installation of google authenticator.
2. Go to settings > app > Authenticator > Permission > remove camera access.
3. Open the app again and click on + button to scan a barcode
4. On the alert message check 'Don't ask again'
5. Allow button will get disabled

Please have a look at the attached video for better understanding of this issue.

[Authenticator_camera_access_issue.mp4.zip](https://github.com/google/google-authenticator/files/3550733/Authenticator_camera_access_issue.mp4.zip)

**Comment by ThomasHabets** [comment]
-> Transferred to Google Authenticator Android project.

I don't think this is a Google Authenticator issue. I think this is simply how Android works and it's part of the OS UI.

My guessing on reason: If you say "Deny" it makes sense to say "and never ask me again", whereas if you say "Allow" it may imply "Don't ask again" since maybe Android does not have a "ask per use". I think iPhone may have that, but I'm not an expert.

If you think of this dialog as asking "can I have access to the camera **from now on**", does it make more sense?

Other apps work this way too. E.g. if you disable camera access for the "Camera" app it'll do the exact same thing.

**Comment by satnam-malhotra** [comment]
Yeah, that makes sense. Thanks for the reply.
