### ISSUE TITLE
Create release please

### ISSUE THREAD

**Issue by Alex1602** [google/google-authenticator-android#12]
There were made serveral bug fixes in since it was placed on github. Please release those to the app market, the fixes were necessary for me to let this app work. i do now have a self compiled apk on my phone....

**Comment by ThomasHabets** [comment]
There are no plans to put the open source version of Google Authenticator on the play store at this time, sorry. The code has diverged from the closed source version that's on the play store for quite some time, and it should be seen as a separate project.

If you're referring to the math bug with exponents (https://github.com/google/google-authenticator-android/pull/4), I pushed for that to be fixed in the play store version, but I don't know the release status of that.

**Comment by Alex1602** [comment]
That is exactly the bug that i was talking about. Is there anyway to keep track of progres?

**Comment by ThomasHabets** [comment]
I'll look into it.

**Comment by ThomasHabets** [comment]
Fix is in. No promises on release date, but "soon".
