### ISSUE TITLE
Where to find updated source code (v4.74)?

### ISSUE THREAD

**Issue by ThmsD** [google/google-authenticator-android#58]
Where do I find the updated source code of the Google Authenticator (v4,74) (with integrated barcode scanner, material design, etc.) as described at the Play Store?
Is it available at all?

**Comment by ocdtrekkie** [comment]
@ThmsD It is not available. Google Authenticator is no longer open source.

**Comment by ThmsD** [comment]
@ocdtrekkie I didn't notice that. Is there a specific reason for this?

**Comment by ThomasHabets** [comment]
You beat me to it. I was going to say something clever like "step one is to get hired by Google", but year it's not opensource.

As for why: The stated reason was "This open source project allows you to download the code that powered version 2.21 of the application. Subsequent versions contain Google-specific workflows that are not part of the project." ([wikipedia](https://en.wikipedia.org/wiki/Google_Authenticator#Open_Source_status_on_Android))

Standard message below:

\--
FYI: The version in Google Play Store / Apple App store is not the same as this opensource version. They've diverged. This opensource version is also unlikely to end up in the app stores. This open source version doesn't get much love, but I'll accept well-written pull requests. But don't expect this feature to be implemented by Google.

**Comment by jyxjjj** [comment]
@ThomasHabets 
But, I don't think it's a 'reason'.
I am so curious.
I don't think the algorithms are difficult to implement.
Cause I wrote a PHP version already.
I don't think the Material Design of it are difficult to implement too,
even Google Authenticator v5.0.0 .
If it's just because you're busy working, or lazy, can i hack/crack its source code?
My JAVA is so poor.
I don't want to use HTML5 App.
If I can only change a name and release i will be very happy.
Please give me some advice?

**Comment by ThomasHabets** [comment]
@jyxjjj it's not my decision to no longer release the source code, and I don't know and can't give any more justification than I've already said.

As for the rest of your questions I'm not a lawyer and can't give legal advice. I can just point you at [the license](https://github.com/google/google-authenticator-android/blob/master/COPYING) and you can judge for yourself.

**Comment by jyxjjj** [comment]
Thanks.
--
> And by the way i didn't mean you, my 'you' means google(you all).
