### ISSUE TITLE
codes not accepted

### ISSUE THREAD

**Issue by the-astronaut** [google/google-authenticator-android#72]
I'm using an android8 phone with GA to log into bitfinex.com. Since my OnePlus3t crashed it resetted to factory, after reinstalling GA my codes aren't accepted on the website anymore. Result I'm financially kept hostage, I can't access my savings. Bitfinex is gone dark and has no support. 

Now nothing changed related to timezones or something like that. 

Is GA related to an emailaddresse?

**Comment by ThomasHabets** [comment]
What was your plan if your phone had been stolen? Probably best to do that. If you trust your savings with amateur money launderers and possibly organized crime then you should have a backup plan.

> after reinstalling GA my codes aren't accepted on the website anymore

How do you have any codes at all after a factory reset?

> Now nothing changed related to timezones or something like that.

Make sure the time is set correctly.

> Is GA related to an emailaddresse?

I'm not sure what the question is. The input to the TOTP algorithm is only the secret and the time.

**Comment by the-astronaut** [comment]
Well my Google Account didn't change at all. So I just downloaded GA again and added the barcode from my Google Account, hence I get new codes. Which doesn't work with my account on Bitfinex. 

I don't understand why it doens't work. My google account isn't changed, my time isn't changed. So why aren't the codes accepted? (I synced the time, it tells me it's already correct)

I added a printscreen of the problem. 
https://i.imgur.com/4DXYkOO.jpg

**Comment by ThomasHabets** [comment]
I don't know how Bitfinex works, but are you saying you had *one* config in GA, that worked for both Google and Bitfinex before the factory reset? That seems… implausible. You more likely had two, and you've now added only one (the one for Google).

But even if that were the case (I don't see how, short of you taking a screenshot of Google's barcode and uploading that screenshot to Bitfinex), when Google issues a new barcode it'll contain a brand new secret.

I'd say your only hope for ever getting into Bitfinex again is:
1) Brute force the OTP code. If this is our of your expertise then hire someone who can. Probably won't work though, because I'd hope Bitfinex blocks what'd be like half a million login attempts. So never mind. Really only one option:
2) Get hold of Bitfinex to have them do account recovery for you.

And this is why we have real banks and regulated institutions for our savings.

**Comment by ThomasHabets** [comment]
Closing because lack of response.

Also https://medium.com/@bitfinexed/bitfinex-fails-to-perform-promised-audits-instead-they-have-a-shareholder-tell-everyone-its-all-965ae7037b5d
